spring:
  application:
    name: cart-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cartDB
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: app.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'