server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: photo-service
          uri: lb://photo-service
          predicates:
            - Path=/photo/**

        - id: user-service-user
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - JWTFilter
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - JWTFilter

        #        API gateway for cart microservice
        - id: cart-service-cart
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - JWTFilter
        - id: cart-service-cartorder
          uri: lb://cart-service
          predicates:
            - Path=/cartorder/**
        - id: cart-service-saveforlater
          uri: lb://cart-service
          predicates:
            - Path=/saveforlater/**
        - id: cart-service-wishlist
          uri: lb://cart-service
          predicates:
            - Path=/wishlist/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

#        API gateway for product microservice
        - id: product-service-product
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: product-service-promotion
          uri: lb://product-service
          predicates:
            - Path=/promotion/**

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**

