spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userDB

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: app.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

app:
  jwt:
    secret-key: ${APP_JWT_SECRET_KEY}