spring:
  application:
    name: photo-service
  config:
    import: "optional:configserver:http://localhost:8088"

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB



